apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  selector:
    app: integration  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8992 
  type: NodePort
