apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integration
  template:
    metadata:
      labels:
        app: integration
    spec:
      containers:
      - name: integration
        image: kb09/integration-service:latest
        ports:
        - containerPort: 8992  
